import { Banner, ProductCard, Wrapper } from "@/components";
import { fetchData } from "@/libs/api";
import Head from "next/head";

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>Nikomex || Sports and Workout Shoes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Banner />
        <Wrapper>
          {/* heading and paragaph start */}
          <div className="text-center max-w-[800px] mx-auto my-[50px] md:my-[80px]">
            <div className="text-[28px] md:text-[34px] mb-5 font-semibold leading-tight">
              Cushioning for Your Miles
            </div>
            <div className="text-md md:text-xl">
              A lightweight Nike ZoomX midsole is combined with increased stack
              heights to help provide cushioning during extended stretches of
              running.
            </div>
          </div>
          {/* heading and paragaph end */}

          {/* products grid section */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5 my-14 px-5 md:px-0">
            {products?.data?.map((product) => (
              <ProductCard key={product?.id} data={product} />
            ))}
          </div>
        </Wrapper>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const products = await fetchData("/api/products?populate=*");

  return {
    props: { products },
  };
}
